# template makefile for ocaml bytecode
OCAML := ocamlc
OPTS  := -g
CLEAN_EXTS := *.cmi *.cmx *.cmo
BINARIES := hellow

all: hellow

hellow: hellow.cmo
	$(OCAML) $(OPTS) -o $@ -c $?

%.cmo: %.ml
	$(OCAML) $(OPTS) -o $@ -c $?

clean:
	rm -rf *.o $(CLEAN_EXTS) $(BINARIES)

.PHONY: clean all
